version: '3.4'

services:
  jobber.app:
    image: ${DOCKER_REGISTRY-}jobberapp
    build:
      context: .
      dockerfile: Jobber.App/Dockerfile
    depends_on:
      - jobber.db
    ports:
      - "80:8080"
      - "443:8081"

  jobber.db:
    image: postgres:15
    environment:
      POSTGRES_DB: jobberdb
      POSTGRES_USER: jobberuser
      POSTGRES_PASSWORD: securepassword
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-data:
